### ISSUE TITLE
Boilerplate

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/easy-wasm-c-example#1]
# Motivation
We want to set up an easy working example.

# Task Implementation
- [x] Install dependencies.
- [x] Add the basic c file.
- [x] Get the basic jest setup working.
- [x] set up the README.
